//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddUser.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materialy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materialy()
        {
            this.Zakazy = new HashSet<Zakazy>();
        }
    
        public int ID_Materiala { get; set; }
        public string Nazvanie_Materiala { get; set; }
        public int Kolvo_Na_Sklade { get; set; }
        public decimal Stoimost_Za_Metr { get; set; }
        public int Cvet_Materiala { get; set; }
        public int Tip_Materiala { get; set; }
        public string Prochnost_Materiala { get; set; }
        public int Postavshik { get; set; }
    
        public virtual Cvet_Materiala Cvet_Materiala1 { get; set; }
        public virtual Postavshiki Postavshiki { get; set; }
        public virtual Tip_Materiala Tip_Materiala1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakazy> Zakazy { get; set; }
    }
}
