//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddUser.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class atelieEntities : DbContext
    {
        public atelieEntities()
            : base("name=atelieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Avtorizacia> Avtorizacia { get; set; }
        public virtual DbSet<Cvet_Materiala> Cvet_Materiala { get; set; }
        public virtual DbSet<Doljnost> Doljnost { get; set; }
        public virtual DbSet<Izdeliya> Izdeliya { get; set; }
        public virtual DbSet<Klienty> Klienty { get; set; }
        public virtual DbSet<Materialy> Materialy { get; set; }
        public virtual DbSet<Modeli> Modeli { get; set; }
        public virtual DbSet<Otchety> Otchety { get; set; }
        public virtual DbSet<Otzyvy> Otzyvy { get; set; }
        public virtual DbSet<Postavshiki> Postavshiki { get; set; }
        public virtual DbSet<Razmer_Odejdy> Razmer_Odejdy { get; set; }
        public virtual DbSet<Skidki> Skidki { get; set; }
        public virtual DbSet<Sklad> Sklad { get; set; }
        public virtual DbSet<Sotrudniki> Sotrudniki { get; set; }
        public virtual DbSet<Status_Zakaza> Status_Zakaza { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tip_Materiala> Tip_Materiala { get; set; }
        public virtual DbSet<Zakazy> Zakazy { get; set; }
    }
}
