//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddUser.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otchety
    {
        public int ID_Otcheta { get; set; }
        public System.DateTime Data_Otcheta { get; set; }
        public string Opisanie_Otcheta { get; set; }
        public string Soderjanie_Otcheta { get; set; }
        public int ID_Sotrudnika { get; set; }
    
        public virtual Sotrudniki Sotrudniki { get; set; }
    }
}
