//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddUser.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otzyvy
    {
        public int ID_Otzyvov { get; set; }
        public int ID_Zakaza { get; set; }
        public int ID_Klienta { get; set; }
        public System.DateTime Data_Otzyva { get; set; }
        public string Soderjanie_Otzyva { get; set; }
        public int Ocenka_Otzyva { get; set; }
    
        public virtual Klienty Klienty { get; set; }
        public virtual Zakazy Zakazy { get; set; }
    }
}
