//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddUser.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sklad
    {
        public int ID_Sklada { get; set; }
        public int ID_Modeli { get; set; }
        public int Kolvo_Na_Sklade { get; set; }
        public System.DateTime Data_Postupleniya { get; set; }
    
        public virtual Modeli Modeli { get; set; }
    }
}
